version: '3.1'

services:
  shopicano_storefront:
    image: docker.pkg.github.com/shopicano/shopicano-dashboard/shopicano-dashboard:1.0.6-rc
    environment:
      - SHOPICANO_BACKEND_URL=https://alpha-api.shopicano.com
    ports:
      - 9100:8080
